- name: Pregnancy Due Date
  state: >
    {% set last_period_date = states('sensor.pregnancy_due_date') | as_datetime %}
    {% set due_date = last_period_date + timedelta(weeks=40) %}
    {{ due_date.strftime('%Y-%m-%d') }}
# - name: "Pregnancy Next Check"
#   state: |
#     {{ state_attr('calendar.baby_calendar', 'start_time') | as_timestamp | timestamp_custom('%-I:%M%p on %a, %B %d') }}"
- name: Pregnancy Days # Total accumulated days while pregnant.
  unit_of_measurement: "days"
  state: >
    {{ (now() - states('input_datetime.pregnancy_last_period') | as_datetime | as_local).days }}
- name: Pregnancy Days Left
  unit_of_measurement: "days"
  state: >
    {{ (states('sensor.pregnancy_due_date') | as_datetime | as_local - now()).days }}
- name: Pregnancy Percent
  unit_of_measurement: "%"
  state: >
    {{ (((states('sensor.pregnancy_days') | int)*100) / ((states('sensor.pregnancy_days') | int)+(states('sensor.pregnancy_days_left') | int))) | int }}
