- name: Pregnancy
  state: |
    {{ states('sensor.pregnancy_days') | int // 7 }}
  attributes:
    day_in_week: |
      {{ states('sensor.pregnancy_days') | int % 7 }}
    trimester: |
      {% set x = (states('sensor.pregnancy_weeks') | int) %}
      {{ 'First' if (x <= 12) else 'Second' if (x <= 28) else 'Third' }}
    days: |
      {{ states('sensor.pregnancy_days') }}
    months: |
      {{ ((states('sensor.pregnancy_days') | int) / 30.5) | round(1, 'half') }}
    percent: |
      {{ states('sensor.pregnancy_percent') }}
    size: |
      {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
      {{ calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset') }}
    size_details: |
      {% from 'userfiles/templates/fruit.jinja' import 'get_size_details' }
      {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
      {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
      {{ get_size_details(size) }}
    size_image_url: |
      {% from 'userfiles/templates/fruit.jinja' import 'get_image_url' }
      {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
      {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
      {{ get_image_url(size) }}
    size_ref_url: |
      {% from 'userfiles/templates/fruit.jinja' import 'get_ref_url' }
      {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
      {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
      {{ get_ref_url(size) }}
    # fetus_size_image: |
    #   https://images.agoramedia.com/wte3.0/gcms/wbw_squares_baby_wk_{{ states('sensor.pregnancy_weeks') }}.jpg
    # fetus_size_fruit_image: |
    #   https://images.agoramedia.com/wte3.0/gcms/wbw-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}-fruit.png
    # fetus_size_fruit: |
    #   {% include 'userfiles/templates/fruit.jinja' %}
    # fetus_size_manly_image: |
    #   https://babysizer.com/manly/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/manly-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
    # fetus_size_manly: |
    #   {% include 'userfiles/templates/cravings.jinja' %}
    # fetus_size_geeky_image: |
    #   https://babysizer.com/geeky/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/geeky-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
    # fetus_size_geeky: |
    #   {% include 'userfiles/templates/cravings.jinja' %}
    # fetus_size_cravings_image: |
    #   https://babysizer.com/cravings/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/cravings-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
    # fetus_size_cravings: |
    #   {% include 'userfiles/templates/cravings.jinja' %}
    # babycenter_link: |
    #   https://www.babycenter.com/pregnancy/week-by-week/{{ states('sensor.pregnancy') }}-weeks-pregnant
    # what_to_expect_link: |
    #   https://www.whattoexpect.com/pregnancy/week-by-week/week-{{ states('sensor.pregnancy_weeks') }}.aspx
    # verywellfamily_link: |
    #   {% include 'verywellfamily_link.jinja' %}
    # manly_link: |
    #   https://babysizer.com/manly/{{ states('sensor.pregnancy_weeks') }}
    # geeky_link: |
    #   https://babysizer.com/geeky/{{ states('sensor.pregnancy_weeks') }}
    # cravings_link: |
    #   https://babysizer.com/cravings/{{ states('sensor.pregnancy_weeks') }}
    # mayo_clinic_link: |
    #   https://www.mayoclinic.org/healthy-lifestyle/pregnancy-week-by-week/in-depth/hlv-20049471
    # fetal_development: |
    #   {% include 'userfiles/templates/development.jinja' %}

