# # INSTRUCTIONS:
# - Add the below to the bottom to your `configuration.yaml` file.
# - copy the `pregnancy` directory to your config folder (where `configuration.yaml` was)  

input_datetime  pregnancy_input_datetimes:  !include "pregnancy/input_datetimes.yaml"
input_number    pregnancy_input_numbers:    !include "pregnancy/input_numbers.yaml"
sensor          pregnancy_sensors:          !include "pregnancy/sensors.yaml"

template:
  - sensor: !include_dir_merge_list "pregnancy/template_sensors"
