default_config:

homeassistant:
  debug: true

logger:
  default: info
  logs:
    custom_components.pregnancy_tracker: debug

sensor:
- platform: folder
  folder: /config/www/baby

template:
  - sensor:
      - name: "Pregnancy Due Date"
        state: "{% include 'due_date.jinja' %}"
      - name: "Pregnancy Next Check"
        state: "{{ state_attr('calendar.baby_calendar', 'start_time') | as_timestamp | timestamp_custom('%-I:%M%p on %a, %B %d') }}"
      - name: "Pregnancy Days" # Total accumulated days while pregnant.
        unit_of_measurement: 'days'
        state: "{{ (now() - states('input_datetime.pregnancy_last_period') | as_datetime | as_local).days }}"
      - name: "Pregnancy Days Left"
        unit_of_measurement: 'days'
        state: "{{ (states('sensor.pregnancy_due_date') | as_datetime | as_local - now()).days }}"
      - name: "Pregnancy Percent"
        unit_of_measurement: '%'
        state: "{{ (((states('sensor.pregnancy_days') | int)*100) / ((states('sensor.pregnancy_days') | int)+(states('sensor.pregnancy_days_left') | int))) | int }}"
      - name: "Pregnancy Fetal Length"
        state: "{% include 'fetus_size/length.jinja' %}"
      - name: "Pregnancy Fetal Weight"
        state: "{% include 'fetus_size/weight.jinja' %}"
      - name: "Pregnancy"
        state: "{{ states('sensor.pregnancy_days') | int // 7 }}"
        attributes:
          day_in_week: "{{ states('sensor.pregnancy_days') | int % 7 }}" # This attribute purposfully calculates day of the week between 0 and 6, following U.S. healthcare standards.
          trimester: "{% include 'trimester.jinja' %}"
          days: "{{ states('sensor.pregnancy_days') }}" 
          months: "{{ ((states('sensor.pregnancy_days') | int) / 30.5) | round(1, 'half') }}"
          percent: "{{ states('sensor.pregnancy_percent') }}"
          fetus_size_image: "https://images.agoramedia.com/wte3.0/gcms/wbw_squares_baby_wk_{{ states('sensor.pregnancy_weeks') }}.jpg"
          fetus_size_fruit_image: "https://images.agoramedia.com/wte3.0/gcms/wbw-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}-fruit.png"
          fetus_size_fruit: "{% include 'fetus_size/fruit.jinja' %}"
          fetus_size_manly_image: "https://babysizer.com/manly/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/manly-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg"
          fetus_size_manly: "{% include 'fetus_size/cravings.jinja' %}"
          fetus_size_geeky_image: "https://babysizer.com/geeky/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/geeky-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg"
          fetus_size_geeky: "{% include 'fetus_size/cravings.jinja' %}"
          fetus_size_cravings_image: "https://babysizer.com/cravings/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/cravings-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg"
          fetus_size_cravings: "{% include 'fetus_size/cravings.jinja' %}"
          babycenter_link: "https://www.babycenter.com/pregnancy/week-by-week/{{ states('sensor.pregnancy') }}-weeks-pregnant"
          what_to_expect_link: "https://www.whattoexpect.com/pregnancy/week-by-week/week-{{ states('sensor.pregnancy_weeks') }}.aspx"
          verywellfamily_link: "{% include 'verywellfamily_link.jinja' %}"
          manly_link: "https://babysizer.com/manly/{{ states('sensor.pregnancy_weeks') }}"
          geeky_link: "https://babysizer.com/geeky/{{ states('sensor.pregnancy_weeks') }}"
          cravings_link: "https://babysizer.com/cravings/{{ states('sensor.pregnancy_weeks') }}"
          mayo_clinic_link: "https://www.mayoclinic.org/healthy-lifestyle/pregnancy-week-by-week/in-depth/hlv-20049471"
          fetal_development: "{% include 'fetus_size/development.jinja' %}"
