default_config:

homeassistant:
  debug: true

logger:
  default: info
  logs:
    custom_components.pregnancy_tracker: debug

sensor:
- platform: folder
  folder: /config/www/baby

## All other pregnancy dashboard sensors are setup as Templates.
template:
  - sensor:
      - name: Pregnancy Due Date
        state: |
          {% from 'pregnancy_tracker.jinja' import 'calc_due_date' %}
          {{ calc_due_date('sensor.pregnancy_due_date') }}
      # - name: "Pregnancy Next Check"
      #   state: |
      #     {{ state_attr('calendar.baby_calendar', 'start_time') | as_timestamp | timestamp_custom('%-I:%M%p on %a, %B %d') }}"
      - name: Pregnancy Days # Total accumulated days while pregnant.
        unit_of_measurement: "days"
        state: |
          {{ (now() - states('input_datetime.pregnancy_last_period') | as_datetime | as_local).days }}
      - name: Pregnancy Days Left
        unit_of_measurement: "days"
        state:
          {{ (states('sensor.pregnancy_due_date') | as_datetime | as_local - now()).days }}
      - name: Pregnancy Percent
        unit_of_measurement: "%"
        state:
          {{ (((states('sensor.pregnancy_days') | int)*100) / ((states('sensor.pregnancy_days') | int)+(states('sensor.pregnancy_days_left') | int))) | int }}
      - name: Pregnancy Fetal Length
        state: |
          {% from 'userfiles/fetus_size/height.jinja' import 'get_size_details' }
          {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
          {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
          {{ get_size_details(size) }}
      - name: Pregnancy Fetal Weight
        state: |
          {% from 'userfiles/fetus_size/weight.jinja' import 'get_size_details' }
          {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
          {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
          {{ get_size_details(size) }}
      - name: Pregnancy
        state: |
          {{ states('sensor.pregnancy_days') | int // 7 }}
        attributes:
          day_in_week: |
            {{ states('sensor.pregnancy_days') | int % 7 }}
          trimester: |
            {% from 'pregnancy_tracker.jinja' import 'calc_trimester' %}
            {{ calc_trimester('sensor.pregnancy_weeks') }}
          days: |
            {{ states('sensor.pregnancy_days') }}
          months: |
            {{ ((states('sensor.pregnancy_days') | int) / 30.5) | round(1, 'half') }}
          percent: |
            {{ states('sensor.pregnancy_percent') }}
          size: |
            {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
            {{ calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset') }}
          size_details: |
            {% from 'userfiles/fetus_size/fruit.jinja' import 'get_size_details' }
            {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
            {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
            {{ get_size_details(size) }}
          size_image_url: |
            {% from 'userfiles/fetus_size/fruit.jinja' import 'get_image_url' }
            {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
            {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
            {{ get_image(size) }}
          size_ref_url: |
            {% from 'userfiles/fetus_size/fruit.jinja' import 'get_ref_url' }
            {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
            {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
            {{ get_ref_url(size) }}
          # fetus_size_image: |
          #   https://images.agoramedia.com/wte3.0/gcms/wbw_squares_baby_wk_{{ states('sensor.pregnancy_weeks') }}.jpg
          # fetus_size_fruit_image: |
          #   https://images.agoramedia.com/wte3.0/gcms/wbw-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}-fruit.png
          # fetus_size_fruit: |
          #   {% include 'userfiles/fetus_size/fruit.jinja' %}
          # fetus_size_manly_image: |
          #   https://babysizer.com/manly/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/manly-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
          # fetus_size_manly: |
          #   {% include 'userfiles/fetus_size/cravings.jinja' %}
          # fetus_size_geeky_image: |
          #   https://babysizer.com/geeky/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/geeky-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
          # fetus_size_geeky: |
          #   {% include 'userfiles/fetus_size/cravings.jinja' %}
          # fetus_size_cravings_image: |
          #   https://babysizer.com/cravings/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/cravings-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
          # fetus_size_cravings: |
          #   {% include 'userfiles/fetus_size/cravings.jinja' %}
          # babycenter_link: |
          #   https://www.babycenter.com/pregnancy/week-by-week/{{ states('sensor.pregnancy') }}-weeks-pregnant
          # what_to_expect_link: |
          #   https://www.whattoexpect.com/pregnancy/week-by-week/week-{{ states('sensor.pregnancy_weeks') }}.aspx
          # verywellfamily_link: |
          #   {% include 'verywellfamily_link.jinja' %}
          # manly_link: |
          #   https://babysizer.com/manly/{{ states('sensor.pregnancy_weeks') }}
          # geeky_link: |
          #   https://babysizer.com/geeky/{{ states('sensor.pregnancy_weeks') }}
          # cravings_link: |
          #   https://babysizer.com/cravings/{{ states('sensor.pregnancy_weeks') }}
          # mayo_clinic_link: |
          #   https://www.mayoclinic.org/healthy-lifestyle/pregnancy-week-by-week/in-depth/hlv-20049471
          # fetal_development: |
          #   {% include 'userfiles/fetus_size/development.jinja' %}
