###########################
### Pregnancy Dashboard ###
###########################

input_datetime:
  pregnancy_last_period:
    name: First Day of Last Period
    has_date: true
    has_time: false

input_number:
  pregnancy_size_offset:
    name: Pregnancy size offset
    max: 42
    min: -42
    step: 1
    mode: box

sensor:
  - platform: folder
    folder: /config/www/baby

template:
  - sensor:

    # Time

    - name: Pregnancy Due Date
      state: >
        {% set last_period_date = states('input_datetime.pregnancy_last_period') | as_datetime %}
        {% set due_date = last_period_date + timedelta(weeks=40) %}
        {{ due_date.strftime('%Y-%m-%d') }}
    # - name: "Pregnancy Next Check"
    #   state: |
    #     {{ state_attr('calendar.baby_calendar', 'start_time') | as_timestamp | timestamp_custom('%-I:%M%p on %a, %B %d') }}"
    - name: Pregnancy Days # Total accumulated days while pregnant.
      unit_of_measurement: "days"
      state: >
        {{ (now() - states('input_datetime.pregnancy_last_period') | as_datetime | as_local).days }}
    - name: Pregnancy Weeks
      unit_of_measurement: "weeks"
      state: >
        {{ states('sensor.pregnancy_days') | int // 7 }}
    - name: Pregnancy Day in Week
      unit_of_measurement: "days"
      state: >
        {{ states('sensor.pregnancy_days') | int % 7 }}
    - name: Pregnancy Days Left
      unit_of_measurement: "days"
      state: >
        {{ (states('sensor.pregnancy_due_date') | as_datetime | as_local - now()).days }}
    - name: Pregnancy Percent
      unit_of_measurement: "%"
      state: >
        {{ (((states('sensor.pregnancy_days') | int)*100) / ((states('sensor.pregnancy_days') | int)+(states('sensor.pregnancy_days_left') | int))) | int }}

    # Size

    - name: Pregnancy Size
      state: >
        {{ states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int }}
    # - name: Pregnancy Fetal Length
    #   state: >
    #     {% from 'pregnancy/height.jinja' import 'get_size_detail' }
    #     {{ get_size_detail(states('sensor.pregnancy_size')) }}
    # - name: Pregnancy Fetal Weight
    #   state: >
    #     {% from 'pregnancy/weight.jinja' import 'get_size_detail' }
    #     {{ get_size_detail(states('sensor.pregnancy_size')) }}

    # Tracker
  
    - name: Pregnancy
      state: >
        {{ states('sensor.pregnancy_weeks') }}
      attributes:
        day_in_week: > # This calculates day of the week between 0 and 6, following U.S. healthcare standards.
          {{ states('sensor.pregnancy_days') | int % 7 }}
        trimester: >
          {% set x = (states('sensor.pregnancy_weeks') | int) %}
          {{ 'First' if (x <= 12) else 'Second' if (x <= 28) else 'Third' }}
        days: >
          {{ states('sensor.pregnancy_days') }}
        months: >
          {{ ((states('sensor.pregnancy_days') | int) / 30.5) | round(1, 'half') }}
        percent: >
          {{ states('sensor.pregnancy_percent') }}
        size: >
          {{ states('sensor.pregnancy_size') }}
        # size_details: |
        #   {% from 'userfiles/templates/fruit.jinja' import 'get_size_details' }
        #   {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
        #   {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
        #   {{ get_size_details(size) }}
        # size_image_url: |
        #   {% from 'userfiles/templates/fruit.jinja' import 'get_image_url' }
        #   {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
        #   {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
        #   {{ get_image_url(size) }}
        # size_ref_url: |
        #   {% from 'userfiles/templates/fruit.jinja' import 'get_ref_url' }
        #   {% from 'pregnancy_tracker.jinja' import 'calc_fetus_size' %}
        #   {% set size = calc_fetus_size('sensor.pregnancy_weeks', 'input_number.pregnancy_size_offset')}
        #   {{ get_ref_url(size) }}
        # fetus_size_image: |
        #   https://images.agoramedia.com/wte3.0/gcms/wbw_squares_baby_wk_{{ states('sensor.pregnancy_weeks') }}.jpg
        # fetus_size_fruit_image: |
        #   https://images.agoramedia.com/wte3.0/gcms/wbw-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}-fruit.png
        # fetus_size_fruit: |
        #   {% include 'userfiles/templates/fruit.jinja' %}
        # fetus_size_manly_image: |
        #   https://babysizer.com/manly/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/manly-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
        # fetus_size_manly: |
        #   {% include 'userfiles/templates/cravings.jinja' %}
        # fetus_size_geeky_image: |
        #   https://babysizer.com/geeky/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/geeky-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
        # fetus_size_geeky: |
        #   {% include 'userfiles/templates/cravings.jinja' %}
        # fetus_size_cravings_image: |
        #   https://babysizer.com/cravings/{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}/cravings-{{ (states('sensor.pregnancy_weeks')|int + states('input_number.pregnancy_size_offset')|int) }}.jpg
        # fetus_size_cravings: |
        #   {% include 'userfiles/templates/cravings.jinja' %}
        # babycenter_link: |
        #   https://www.babycenter.com/pregnancy/week-by-week/{{ states('sensor.pregnancy') }}-weeks-pregnant
        # what_to_expect_link: |
        #   https://www.whattoexpect.com/pregnancy/week-by-week/week-{{ states('sensor.pregnancy_weeks') }}.aspx
        # verywellfamily_link: |
        #   {% include 'verywellfamily_link.jinja' %}
        # manly_link: |
        #   https://babysizer.com/manly/{{ states('sensor.pregnancy_weeks') }}
        # geeky_link: |
        #   https://babysizer.com/geeky/{{ states('sensor.pregnancy_weeks') }}
        # cravings_link: |
        #   https://babysizer.com/cravings/{{ states('sensor.pregnancy_weeks') }}
        # mayo_clinic_link: |
        #   https://www.mayoclinic.org/healthy-lifestyle/pregnancy-week-by-week/in-depth/hlv-20049471
        # fetal_development: |
        #   {% include 'userfiles/templates/development.jinja' %}
    
     
